
#General settings.
[general]
	#Using embedded skin renderer to replace the original item renderer.
	#0 = auto
	#1 = disable
	#2 = enable
	#Range: 0 ~ 2
	enableEmbeddedSkinRenderer = 0
	#Using skin renderer to replace the original first person hands renderer.
	#0 = auto
	#1 = always disable
	#2 = always enable
	#Range: 0 ~ 2
	enableFirstPersonSkinRenderer = 0

#Miscellaneous settings.
[misc]
	#How long skins will display their loading animation for in milliseconds
	#Settings this to 0 will disable loading animations.
	#Range: 0 ~ 10000
	skinLoadAnimationTime = 200
	#Whether allows skin to limit limbs of entities.
	enableSkinLimitLimbs = true
	#Whether clip the excess skin in the inventory gui.
	enableClipInInventory = true

#Change (visual quality/performance) ratio by changing setting in this category.
[performance]
	#The max distance in blocks that skins will render.
	#Range: 16 ~ 512
	renderDistanceSkin = 128
	#The max distance in blocks that block skins will be rendered.
	#Range: 16 ~ 512
	renderDistanceBlockSkin = 128
	#The max distance in blocks that equipment will be rendered on mannequins.
	#Range: 16 ~ 512
	renderDistanceMannequinEquipment = 64
	#The maximum number of threads that will be used to bake models. 
	#[range: 1 ~ 16, default: core count / 2]
	#Range: 1 ~ 16
	modelBakingThreadCount = 12
	#When enabled skin will render in multiple passes to reduce visual artifacts.
	#Disabling this will improve skin rendering performance at the cost of visual quality.
	multipassSkinRendering = true
	#Distance away that skins will have lod applied to them.
	#Range: 8.0 ~ 128.0
	lodDistance = 32.0
	#Number of LOD models to create. Higher number should give a boost to framerate at a small cost to VRAM.
	#Range: 0 ~ 4
	maxLodLevels = 4

#Change (memory use/IO access) ratio by changing setting in this category.
[cache]
	#How long in seconds the client will keep skins in it's cache.
	#Default 600 seconds is 10 minutes.
	#Setting to 0 turns off this option.
	#Range: 0 ~ 3600
	skinCacheExpireTime = 600
	#Max size the skin cache can reach before skins are removed.
	#Setting to 0 turns off this option.
	#Range: 0 ~ 10000
	skinCacheMaxSize = 2000
	#How long in seconds the client will keep model parts in it's cache.
	#Default 600 seconds is 10 minutes.
	#Setting to 0 turns off this option.
	#Range: 0 ~ 3600
	modelPartCacheExpireTime = 600
	#Max size the cache can reach before model parts are removed.
	#Setting to 0 turns off this option.
	#Range: 0 ~ 10000
	modelPartCacheMaxSize = 2000
	#How long in seconds the client will keep textures in it's cache
	#Default 600 seconds is 10 minutes.
	#Setting to 0 turns off this option.
	#Range: 0 ~ 3600
	textureCacheExpireTime = 600
	#Max size the texture cache can reach before textures are removed.
	#Setting to 0 turns off this option.
	#Range: 0 ~ 5000
	textureCacheMaxSize = 1000
	#Maximum number of skin the client can request at one time.
	#Range: 1 ~ 50
	maxSkinRequests = 10
	#Size of client size cache.
	#Setting to 0 turns off this option.
	#Range: > 0
	fastCacheSize = 5000

#Setting to configure the skin preview box.
[skin-preview]
	#Enables a larger skin preview box when hovering the mouse over a skin.
	skinPreEnabled = true
	#Draw a background box for the skin preview.
	skinPreDrawBackground = true
	#Size of the skin preview.
	#Range: 16 ~ 256
	skinPreSize = 96
	#Horizontal location of the skin preview: 0 = left, 1 = right.
	#Range: 0.0 ~ 1.0
	skinPreLocHorizontal = 0.0
	#Vertical location of the skin preview: 0 = top, 1 = bottom.
	#Range: 0.0 ~ 1.0
	skinPreLocVertical = 0.5
	#Skin preview will be rendered next to the mouse.
	skinPreLocFollowMouse = true

#Setting to configure tooltips on skinned items.
[tooltip]
	#Show has skin tooltip on skinned items.
	tooltipHasSkin = true
	#Show skin name tooltip on items.
	tooltipSkinName = true
	#Show skin author tooltip on items.
	tooltipSkinAuthor = true
	#Show skin type tooltip on items.
	tooltipSkinType = true
	#Show skin flavoue text tooltip on items.
	tooltipFlavour = true
	#Show open wardrobe message on skins.
	tooltipOpenWardrobe = true

#Debug Settings.
[debug]
	#Shows shader mixin results in logs.
	shader = false
	#Shows extra info on the F3 debug screen.
	showF3DebugInfo = true
	#Texture painting replacing the players texture with a painted version.
	#Turning this off may fix issues with the players texture rendering
	#incorrectly or showing the steve skin.
	#
	#-1 = disabled
	#0 = auto
	#1 = texture_replace (replaces the players texture - LEGACY)
	#2 = model_replace_mc (render using a mc model - slower, more compatible - NOT IMPLEMENTED)
	#3 = model_replace_aw (render using a aw model - faster, less compatible)
	#Range: -1 ~ 2
	texturePaintingType = 0

