
#Common config settings
[common]

	[common.backpackSettings]
		enableTierUpgrades = true
		enableCraftingUpgrade = true
		#New backpacks will have crafting grid by default
		craftingUpgradeByDefault = false
		craftingSavesItems = true
		#Enables wearing backpack directly from ground
		enableBackpackBlockWearable = true
		#Enables unequipping the backpack when player clicks with empty hand on the ground
		enableBackpackRightClickUnequip = false
		#Backpack immune to any damage source (lava, fire), can't be destroyed, never disappears as floating item
		invulnerableBackpack = true
		toolSlotsAcceptSwords = true
		#List of items that can be put in tool slots (Use registry names, for example: minecraft:apple, minecraft:flint)
		toolSlotsAcceptableItems = []
		#Tool slots accept any item
		toolSlotsAcceptEverything = false
		#List of items that can't be put in backpack inventory (Use registry names, for example: minecraft:apple, minecraft:flint)
		blacklistedItems = []
		allowShulkerBoxes = false
		#Prevents backpack disappearing in void
		voidProtection = true
		#Places backpack at place where player died
		backpackDeathPlace = true
		#Places backpack at place where player died, replacing all blocks that are breakable and do not have inventory (backpackDeathPlace must be true in order to work)
		backpackForceDeathPlace = false
		enableSleepingBagSpawnPoint = false
		#If true, backpack can only be worn by placing it in curios 'Back' slot
		#WARNING - Remember to TAKE OFF BACKPACK BEFORE enabling or disabling this integration!! - if not you'll lose your backpack
		curiosIntegration = false

		#Leather Tier Backpack Settings
		[common.backpackSettings.leatherTierBackpack]
			#Number of inventory slots for the tier
			#Range: 1 ~ 63
			inventorySlotCount = 27
			#Number of tool slots for the tier
			#Range: 0 ~ 6
			toolSlotCount = 2
			#Tank capacity for the tier, 1000 equals 1 Bucket
			#Range: 1 ~ 128000
			tankCapacity = 3000

		#Iron Tier Backpack Settings
		[common.backpackSettings.ironTierBackpack]
			#Number of inventory slots for the tier
			#Range: 1 ~ 63
			inventorySlotCount = 36
			#Number of tool slots for the tier
			#Range: 0 ~ 6
			toolSlotCount = 3
			#Tank capacity for the tier, 1000 equals 1 Bucket
			#Range: 1 ~ 128000
			tankCapacity = 4000

		#Gold Tier Backpack Settings
		[common.backpackSettings.goldTierBackpack]
			#Number of inventory slots for the tier
			#Range: 1 ~ 63
			inventorySlotCount = 45
			#Number of tool slots for the tier
			#Range: 0 ~ 6
			toolSlotCount = 4
			#Tank capacity for the tier, 1000 equals 1 Bucket
			#Range: 1 ~ 128000
			tankCapacity = 5000

		#Diamond Tier Backpack Settings
		[common.backpackSettings.diamondTierBackpack]
			#Number of inventory slots for the tier
			#Range: 1 ~ 63
			inventorySlotCount = 54
			#Number of tool slots for the tier
			#Range: 0 ~ 6
			toolSlotCount = 5
			#Tank capacity for the tier, 1000 equals 1 Bucket
			#Range: 1 ~ 128000
			tankCapacity = 6000

		#Netherite Tier Backpack Settings
		[common.backpackSettings.netheriteTierBackpack]
			#Number of inventory slots for the tier
			#Range: 1 ~ 63
			inventorySlotCount = 63
			#Number of tool slots for the tier
			#Range: 0 ~ 6
			toolSlotCount = 6
			#Tank capacity for the tier, 1000 equals 1 Bucket
			#Range: 1 ~ 128000
			tankCapacity = 7000

	[common.world]
		#Enables backpacks spawning in loot chests
		enableLoot = true
		#Enables chance to spawn Zombie, Skeleton, Wither Skeleton, Piglin or Enderman with random backpack equipped
		spawnEntitiesWithBackpack = true
		#List of overworld entity types that can spawn with equipped backpack. DO NOT ADD anything to this list, because the game will crash, remove entries if mob should not spawn with backpack
		possibleOverworldEntityTypes = ["minecraft:zombie", "minecraft:skeleton", "minecraft:enderman"]
		#List of nether entity types that can spawn with equipped backpack. DO NOT ADD anything to this list, because the game will crash, remove entries if mob should not spawn with backpack
		possibleNetherEntityTypes = ["minecraft:wither_skeleton", "minecraft:piglin"]
		#Defines spawn chance of entity with backpack (1 in [selected value])
		#Range: > 0
		spawnChance = 500
		#List of backpacks that can spawn on overworld mobs
		overworldBackpacks = ["travelersbackpack:standard", "travelersbackpack:diamond", "travelersbackpack:gold", "travelersbackpack:emerald", "travelersbackpack:iron", "travelersbackpack:lapis", "travelersbackpack:redstone", "travelersbackpack:coal", "travelersbackpack:bookshelf", "travelersbackpack:sandstone", "travelersbackpack:snow", "travelersbackpack:sponge", "travelersbackpack:cake", "travelersbackpack:cactus", "travelersbackpack:hay", "travelersbackpack:melon", "travelersbackpack:pumpkin", "travelersbackpack:creeper", "travelersbackpack:enderman", "travelersbackpack:skeleton", "travelersbackpack:spider", "travelersbackpack:bee", "travelersbackpack:wolf", "travelersbackpack:fox", "travelersbackpack:ocelot", "travelersbackpack:horse", "travelersbackpack:cow", "travelersbackpack:pig", "travelersbackpack:sheep", "travelersbackpack:chicken", "travelersbackpack:squid"]
		#List of backpacks that can spawn on nether mobs
		netherBackpacks = ["travelersbackpack:quartz", "travelersbackpack:nether", "travelersbackpack:blaze", "travelersbackpack:ghast", "travelersbackpack:magma_cube", "travelersbackpack:wither"]
		#Enables trade for Villager Backpack in Librarian villager trades
		enableVillagerTrade = true

	[common.backpackAbilities]
		enableBackpackAbilities = true
		forceAbilityEnabled = false
		#List of backpacks that are allowed to have an ability. DO NOT ADD anything to this list, because the game will crash, remove entries if backpack should not have ability
		allowedAbilities = ["travelersbackpack:netherite", "travelersbackpack:diamond", "travelersbackpack:gold", "travelersbackpack:emerald", "travelersbackpack:iron", "travelersbackpack:lapis", "travelersbackpack:redstone", "travelersbackpack:bookshelf", "travelersbackpack:sponge", "travelersbackpack:cake", "travelersbackpack:cactus", "travelersbackpack:melon", "travelersbackpack:pumpkin", "travelersbackpack:creeper", "travelersbackpack:dragon", "travelersbackpack:enderman", "travelersbackpack:blaze", "travelersbackpack:ghast", "travelersbackpack:magma_cube", "travelersbackpack:spider", "travelersbackpack:wither", "travelersbackpack:bat", "travelersbackpack:bee", "travelersbackpack:ocelot", "travelersbackpack:cow", "travelersbackpack:chicken", "travelersbackpack:squid"]

	[common.slownessDebuff]
		#Player gets slowness effect, if carries too many backpacks in inventory
		tooManyBackpacksSlowness = false
		#Maximum number of backpacks, which can be carried in inventory, without slowness effect
		#Range: 1 ~ 37
		maxNumberOfBackpacks = 3
		#Range: 0.1 ~ 5.0
		slownessPerExcessedBackpack = 1.0

